project:
  type: website
  output-dir: docs

website:
  description: "EDCI 337 Mirror Site"
  site-url: https://cmadland.github.io/edci337 # you must change this appropriately for RSS feeds to work properly
  title: "EDCI337 Mirror Site"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cmadland/edci337
      - icon: bluesky
        href: https://bsky.app/profile/cmad.land
      - icon: rss
        href: index.xml
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Education Competencies"
        contents:
          - text+image.qmd
          - storytelling.qmd
      - section: Assignments
        contents:
          - multimedia-story-1.qmd  
          - daily-creates.qmd 
          - text: "Assessment"
            href: "https://cmadland.github.io/blog/posts/solo/"
      - section: "Learner Blogs"
        contents:
          - feeds.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true



