---
title: "Multimedia Story DRAFT"
author: "Colin Madland"
date-modified: 2026-05-22
license: "CC-BY"
bibliography: refs.bib
---


You will create a multimedia story during EDCI337. Your story will be your original work and will incorporate media that you have created. You may choose from a wide variety of formats for your story, and the key is that you need to use at least three media formats.

This first component of the story is worth 20% of your final grade and is the first draft of your story.

You are encouraged to tell your story about an adventure you have taken. Adventures sometimes entail some sort of risk and uncertainty of outcome, but that is NOT what I am asking for in this assignment. Do not put yourself in harm’s way for this assignment. However, I do want you to enjoy your adventure and for it to be something that is exciting for you and that is outside and preferably free of charge. ‘Adventure’ is going to be radically different for each person in the class. [For some of you, going for a walk through Finnerty Gardens at UVic with an audio recorder, a notebook and a pencil to sketch birds or plants and/or write a poem will be perfectly suited to this assignment.](https://www.uvic.ca/finnerty/assets/docs/FinnertyGardensWalkingTour.pdf) Others may need something of a different flavour like a bicycle ride, hike, sea kayak voyage, or [what do you want to do?]

You are welcomed and encouraged (but not required) to engage in this adventure with someone else in your learning pod, or your family, or a friend.

## Draft Requirements (Due May 25)
- You are responsible for your safety during this activity.  
- A plan for your adventure (Where will you go? What equipment do you need? Do you need to scout the location?). 
- What will be the shape of the story?  
- What kind of media will you produce?   - How do you plan to integrate the media in alignment with Mayer’s Principles of Multimedia Learning?
- You may choose to engage in a trial of your adventure and gather some sample media.  
- **Importantly, narrate your process!** Tell me and your fellow learners what decisions you made and why. Tell us the challenges you faced and how you overcame them.  
- Publish your draft as a post on your blog.  

## Full Requirements (Due June 15)
- You are responsible for your own safety during this activity.  
- Aim to budget at least one hour on your adventure, including time to gather or create media.  
- You should budget several more hours to create your story.  
- You must integrate at least three media formats into your final story (text, image, audio, video, comics, etc).  
- You must be explicit about how the media you use align with at least four of Mayer’s Principles of Multimedia Learning (redundancy, coherence, signaling, contiguity, segmenting, pretraining, modality).  
- Tell your audience how you incorporated peer feedback into your final draft.  
- **Importantly, narrate your process!** Tell me and your fellow learners what decisions you made and why. Tell us the challenges you faced and how you overcame them.  
- Publish your final draft as a new post on your blog (do not overwrite your draft).